### ISSUE TITLE
Submitting workflows from the catalog does not work

### ISSUE THREAD

**Issue by mbenguig** [ow2-proactive/scheduling-portal#329] opened 2016-10-17 13:30 UTC
From the Scheduler portail, when you click on "submit job", and select a template from the catalog, whence validating the submission, the job does not appear in the "Executions list".

**Comment by tobwiens** [comment] 2016-10-18 07:21
I close this issue due to:  duplicate of #310.

**Closed by tobwiens** 2016-10-18 07:21 UTC
Labels: type:bug
